# Generated by Django 5.0.3 on 2024-03-11 20:31

from django.db import migrations, models

import image_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ("image_uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageuploadaccesskey",
            name="key",
            field=models.CharField(default=image_uploader.models.get_key, help_text="The unique key for a given user to access the upload API", max_length=128, unique=True),
        ),
    ]
